import 'antd/es/menu/style/css'
import 'antd/es/icon/style/css'
import 'antd/es/layout/style/css'
import 'antd/es/breadcrumb/style/css'
import 'antd/es/button/style/css'

export { default as Menu } from 'antd/es/menu'
export { default as Icon } from 'antd/es/icon'
export { default as Layout } from 'antd/es/layout'
export { default as Breadcrumb } from 'antd/es/breadcrumb'
export { default as Button } from 'antd/es/button'
